### ISSUE TITLE
Update crates.io examples & quickstart links

### ISSUE THREAD

**Issue by VanillaBrooks** [elephantry/elephantry#1]
on crates.io, the links for the quickstart.md and examples directory currently 404. 

Current quickstart link: 
https://github.com/sanpii/elephantry/tree/master/core/blob/master/docs/quickstart.md
Current examples link:
https://github.com/sanpii/elephantry/tree/master/core/blob/master/core/examples

Links should probably be identical to the ones in the readme.

**Comment by sanpii** [comment]
Thank you, I hope this will fixed when the next release is published.
